/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_demo_HelloWorld */

#ifndef _Included_com_jni_demo_HelloWorld
#define _Included_com_jni_demo_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_demo_HelloWorld
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_demo_HelloWorld_hello
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jni_demo_HelloWorld
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_demo_HelloWorld_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_jni_demo_HelloWorld
 * Method:    sub
 * Signature: (FD)D
 */
JNIEXPORT jdouble JNICALL Java_com_jni_demo_HelloWorld_sub
  (JNIEnv *, jobject, jfloat, jdouble);

/*
 * Class:     com_jni_demo_HelloWorld
 * Method:    sum_tiny
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_demo_HelloWorld_sum_1tiny
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_jni_demo_HelloWorld
 * Method:    sum_large
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_demo_HelloWorld_sum_1large
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
